#!/data/data/com.termux/files/usr/bin/bash
function Coloring {
NC='\033[0m'
LRED='\033[1;31m'
LGREEN='\033[1;32m'
YELLOW='\033[1;33m'
PURPLE='\033[1;35m'
LBLUE='\033[1;36m'
}

# BANNER
banner() {
toilet "$(figlet "INDIAN TOOL")" -f term --gay  | pv -qL 3000
toilet "  𝗧𝗘𝗟𝗘𝗚𝗥𝗔𝗠 𝗖𝗛𝗔𝗡𝗡𝗘𝗟 𝗜𝗡𝗗𝗜𝗔𝗡 𝗧𝗢𝗢𝗟  " -f term -F border --gay  | pv -qL 3000
toilet -f term -F gay "   PAK-OBB TOOL FREE " | pv -qL 2999
toilet -f term -F gay "   COPYRIGHT BY @INDIAN_TOOL " | pv -qL 2999
toilet -f term -F gay "   TG ADMIN: https://t.me/indian_tool " | pv -qL 2999
}

function identy {
    printf "\n"
    echo -e "${LRED}   𝗖𝗛𝗘𝗖𝗞𝗜𝗡𝗚 𝗨𝗦𝗘𝗥 ${NC}"

    # Check for network connection
    if wget -q --spider http://google.com
    then
        prompt="   𝗘𝗡𝗧𝗘𝗥 𝗣𝗔𝗦𝗦𝗪𝗢𝗥𝗗:"
        password=""

        while IFS= read -p "$prompt" -r -s -n 1 char
        do
            if [[ $char == $'\0' ]]; then
                break
            fi
            if [[ $char == $'\177' ]]; then
                # Handle backspace key
                if [[ -n "$password" ]]; then
                    password="${password%?}"
                    prompt=$'\b \b'
                fi
            else
                prompt='*'
                password+="$char"
            fi
        done
        echo " "

        # Check if the password matches "INDIANTOOL"
        if [[ "$password" == "INDIANTOOL" ]]
        then
            echo -e "${LGREEN}   Access granted. ${NC}"
        else
            printf "\n"
            echo -e "${LRED}Incorrect password. Please try again."
            exit  # Exit immediately if the password is incorrect
        fi
    else
        printf "\n"
        echo -e "${LRED}NO CONNECTION ${NC}"
        exit
    fi
}

chmod +x script/*.bms

# ADD FOLER 
mkdir -p /sdcard/Download/OBB/{REPACK,UNPACK}

UNPACK="/sdcard/Download/INDIAN-TOOL/UNPACK"
OBB="/sdcard/Download/INDIAN-TOOL/OUTOBB"
REPACK="/sdcard/Download/INDIAN-TOOL/REPACK"

# FUNCTION UNAPACK OBB
unpackingpak () {
qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files script/INDIAN-TOOL.bms $UNPACK/$(basename "$selected_file") $OBB
}

# FUNCTION REPACK OBB
repackingpak () {
qemu-i386 $PREFIX/share/quickbms/quickbms_4gb_files -w -r script/INDIAN-TOOL.bms $selected_file /sdcard/Download/INDIAN-TOOL/REPACK
}


# FUNCTION START UNPACK
function unpackpak {
toilet -f term -F gay "𝗬𝗢𝗨 𝗣𝗜𝗖𝗞𝗘𝗗 𝗢𝗣𝗧𝗜𝗢𝗡 𝗨𝗡𝗣𝗔𝗖𝗞"
prompt="𝗦𝗘𝗟𝗘𝗖𝗧 𝗢𝗣𝗧𝗜𝗢𝗡 : "
options=($(find /sdcard/Download/INDIAN-TOOL/UNPACK -name "*.pak" -o -name "*.obb"))
PS3="$prompt "
select opt in "${options[@]}" "Back" ; do
if (( REPLY == 1 + ${#options[@]} )) ; then
break
elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
selected_file="${options[$REPLY-1]}"
echo "You picked $selected_file which is file $REPLY"
mkdir -p "$UNPACK"
cp "$selected_file" "$UNPACK/"
unpackingpak
rm -rf $UNPACK
printf "
"
count=0
  total=3
  start=`date +%s`
  while [ $count -lt $total ]
  do
    sleep 1 # this is work
    cur=`date +%s`
    count=$(( $count + 1 ))
    pd=$(( $count * 73 / $total ))
    runtime=$(( $cur-$start ))
    estremain=$(( ($runtime * $total / $count)-$runtime ))
    printf "\r%d.%d%% complete - est %d:%0.2d remaining\e[K" $(( $count*100/$total )) $(( ($count*1000/$total)%10)) $(( $estremain/60 )) $(( $estremain%60 ))
  done
echo ""
printf "
"   
toilet -f term -F gay "𝗨𝗡𝗣𝗔𝗖𝗞 𝗣𝗔𝗞 𝗗𝗢𝗡𝗘 " | pv -qL 2999
printf "
"   
toilet -f term -F gay "𝗙𝗜𝗟𝗘 𝗜𝗦 𝗦𝗔𝗩𝗘𝗗 𝗜𝗡 𝗛𝗢𝗠𝗘/𝗜𝗡𝗗𝗜𝗔𝗡-𝗧𝗢𝗢𝗟/𝗢𝗨𝗧𝗢𝗕𝗕 " | pv -qL 2999
printf "
"
toilet -f term -F gay "𝗘𝗫𝗜𝗧 𝗧𝗢𝗢𝗟....." | pv -qL 2999
printf "
"
exit
else
echo "𝗜𝗻𝘃𝗮𝗹𝗶𝗱 𝗢𝗽𝘁𝗶𝗼𝗻"
fi
done
}

# FUNCTION START REPACK
function repackpak {
toilet -f term -F gay "𝗬𝗢𝗨 𝗣𝗜𝗖𝗞𝗘𝗗 𝗢𝗣𝗧𝗜𝗢𝗡 𝗥𝗘𝗣𝗔𝗖𝗞 𝟭"
prompt="𝗦𝗘𝗟𝗘𝗖𝗧 𝗢𝗣𝗧𝗜𝗢𝗡 : "
options=($(find /sdcard/Download/INDIAN-TOOL/UNPACK -name "*.pak" -o -name "*.obb"))
PS3="$prompt "
select opt in "${options[@]}" "Back" ; do
if (( REPLY == 1 + ${#options[@]} )) ; then
break
elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
selected_file="${options[$REPLY-1]}"
echo "You picked $selected_file which is file $REPLY"
repackingpak
printf "
"
 count=0
  total=3
  start=`date +%s`
  while [ $count -lt $total ]
  do
    sleep 1 # this is work
    cur=`date +%s`
    count=$(( $count + 1 ))
    pd=$(( $count * 73 / $total ))
    runtime=$(( $cur-$start ))
    estremain=$(( ($runtime * $total / $count)-$runtime ))
    printf "\r%d.%d%% complete - est %d:%0.2d remaining\e[K" $(( $count*100/$total )) $(( ($count*1000/$total)%10)) $(( $estremain/60 )) $(( $estremain%60 ))
  done
echo ""
printf "
"
toilet -f term -F gay "𝗥𝗘𝗣𝗔𝗖𝗞 𝗣𝗔𝗞 𝗗𝗢𝗡𝗘 " | pv -qL 2999
printf "
"   
toilet -f term -F gay "𝗙𝗜𝗟𝗘 𝗜𝗦 𝗦𝗔𝗩𝗘𝗗 𝗜𝗡 𝗗𝗢𝗪𝗡𝗟𝗢𝗔𝗗/𝗢𝗕𝗕/𝗨𝗡𝗣𝗔𝗖𝗞 " | pv -qL 2999
printf "
"
toilet -f term -F gay "𝗘𝗫𝗜𝗧 𝗧𝗢𝗢𝗟....." | pv -qL 2999
printf "
"
exit
else
echo "𝗜𝗻𝘃𝗮𝗹𝗶𝗱 𝗢𝗽𝘁𝗶𝗼𝗻"
fi
done
}

# MAIN MENU PAK MODE
function main {
toilet "  𝗧𝗢𝗢𝗟 𝗨𝗡𝗣𝗔𝗖𝗞 𝗢𝗕𝗕 𝗣𝗨𝗕𝗚 𝗕𝗚𝗠𝗜  " -f term -F border --gay  | pv -qL 3000
PS3='𝗦𝗘𝗟𝗘𝗖𝗧 𝗢𝗣𝗧𝗜𝗢𝗡 : '
options=("$(echo -e "${PURPLE}𝗨𝗡𝗣𝗔𝗖𝗞${NC}\n")" "$(echo -e "${LBLUE}𝗥𝗘𝗣𝗔𝗖𝗞${NC}\n")" "$(echo -e "${YELLOW}𝗘𝗫𝗜𝗧${NC}\n")")
select opt in "${options[@]}"
do
 case $opt in
    "$(echo -e "${PURPLE}𝗨𝗡𝗣𝗔𝗖𝗞${NC}\n")")
      unpackpak
     ;;
    "$(echo -e "${LBLUE}𝗥𝗘𝗣𝗔𝗖𝗞${NC}\n")")
      repackpak
    ;;
    "$(echo -e "${YELLOW}𝗘𝗫𝗜𝗧${NC}\n")")
      break
    ;;
     *) echo "𝗜𝗻𝘃𝗮𝗹𝗶𝗱 𝗢𝗽𝘁𝗶𝗼𝗻 $REPLY";;
  esac
done
}

clear
Coloring
banner
identy
sleep 0.2
main
